version: '3.8'

services:
  db:
    image: postgres:16
    container_name: real_estate_db
    restart: always
    environment:
      POSTGRES_DB: realestate_db
      POSTGRES_USER: realestate
      POSTGRES_PASSWORD: commander123
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  searxng:
    image: searxng/searxng:latest
    container_name: real_estate_searxng
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml
    environment:
      SEARXNG_SETTINGS_PATH: /etc/searxng/settings.yml

volumes:
  db_data:
