# searxng/settings.yml
instance_name: "Real Estate Commander SearXNG"

# Bind to all interfaces for Docker
bind_address: "0.0.0.0"

# Enable general category for broad searches
categories:
  - general
  - map # Keep map category for geocoding

# Engines - you can customize these later
# For now, we'll rely on SearXNG's defaults, which include many search engines.
# If you want to explicitly enable/disable engines, you would list them here.
# For example:
# engines:
#   - google
#   - duckduckgo
#   - bing
#   - openstreetmap

# Preferences (optional)
# results_on_new_tab: true
# autocomplete: "google"
